#! /bin/sh

# █████
#▒▒███
# ▒███████   █████  ████████  █████ ███ █████ █████████████   ████████   ██████
# ▒███▒▒███ ███▒▒  ▒▒███▒▒███▒▒███ ▒███▒▒███ ▒▒███▒▒███▒▒███ ▒▒███▒▒███ ███▒▒███
# ▒███ ▒███▒▒█████  ▒███ ▒███ ▒███ ▒███ ▒███  ▒███ ▒███ ▒███  ▒███ ▒▒▒ ▒███ ▒▒▒
# ▒███ ▒███ ▒▒▒▒███ ▒███ ▒███ ▒▒███████████   ▒███ ▒███ ▒███  ▒███     ▒███  ███
# ████████  ██████  ▒███████   ▒▒████▒████    █████▒███ █████ █████    ▒▒██████
#▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒   ▒███▒▒▒     ▒▒▒▒ ▒▒▒▒    ▒▒▒▒▒ ▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒      ▒▒▒▒▒▒
#                   ▒███
#                   █████
#                  ▒▒▒▒▒

#------------------------------------
# Start-up programmes
#------------------------------------
bspc rule -r "*"
sxhkd &
dunst &
polybar main &
picom --experimental-backends & 

# WAL
wal -R
. "${HOME}/.cache/wal/colors.sh"

#---------------------
# Shell envs
#---------------------
export monitor1="eDP"
export monitor2="VGA-0"
export padding=15

#-------------------------------------
# Display config
#-------------------------------------
xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode VGA-0 "1920x1080_60.00"
xrandr --output $monitor2 --mode "1920x1080_60.00"
xrandr --output $monitor1 --mode "1920x1080"
#bspc monitor $monitor2 -d I  
bspc monitor $monitor2 -d 1 2 3 4 

#-------------------------------------
# bspwm configs
#-------------------------------------
bspc config window_gap                    10
bspc config border_width                  2
bspc config split_ratio                   0.52
bspc config border_radius                 0
bspc config bottom_padding                $padding
bspc config top_padding                   $padding
bspc config left_padding                  $padding
bspc config right_padding                 $padding
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config click_to_focus                true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config normal_border_color           "$color1"
bspc config active_border_color           "$color2"
bspc config focused_border_color          "$color15"
bspc config presel_feedback_color         "$color1"
bspc config urgent_border_color           "#dd2727"

#--------------------------------------
# CUSTOM
#--------------------------------------

#Background
feh --bg-fill $wallpaper

#--------------------------------------
# Program Rules
#--------------------------------------
bspc rule -a alacritty state=floating follow=on center=false sticky=off

#--------------------------------------
# Other
#--------------------------------------
# Remove x cursor
xsetroot -cursor_name left_ptr &

#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
bash /home/jothamsoboyejo/.config/bspwm/bspwm_colors.sh &
